title: "My website"
description: "Hi, I'm Giulia, a phd student at Weizmann Institute of science"
url: "https://carra99.github.io"
remote_theme: "mmistakes/so-simple-theme"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
